name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # 或者你存放源代码的主分支名称

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Debug output
      run: |
        echo "Ruby version: $(ruby -v)"
        echo "Bundler version: $(bundle -v)"
        bundle exec jekyll doctor  
          
    - name: Clear bundler cache
      run: rm -rf vendor/bundle    

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'  # 根据你的需求调整 Ruby 版本
        bundler-cache: true   # 自动缓存 gems 加速构建

    - name: Build Jekyll site
      run: |
        bundle install
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # 构建输出目录
        commit_message: "Deploy Jekyll site [skip ci]"